import os
import random
import time


def defasolution(x):
    if x==1:
        return "AI technologies can help farmers increase crop yields, address the challenges of soil health and herbicide resistance and use resources more sustainably and efficiently to decrease the agricultural sector’s overall greenhouse gas emissions."
    elif x==2:
        return "One of the ways AI is helping to conserve oceans is by fighting plastic pollution with machine learning. Machine learning tackles one of the biggest challenges of combating plastic pollution which is tracking and measuring how exactly it gets into bodies of water."
    elif x==3:
        return "A project Capgemini Invent has been working on in France for two years, TrauMatrix, seeks to provide decision support to doctors treating trauma patients in the first 24 hours. Using a database of road accident victims, the solution aims to parse more data than normally collected to make ultraspecific contextual decisions for emergency surgeries."
    elif x==4:
        return "AI education helps students develop agency to make a change in tomorrow's world, which will require the ability to identify problems, generate creative solutions and work collaboratively across multi-cultural teams."
    elif x==5:
        return "If more women contribute in the AI dataset it will have holes in he AI's knowledge, this is why bias errors happen. Machine learning is, of course, led by humans which means that their own bias will be incorporated whithin the AI system."
    elif x==6:
        return "Clean Water AI uses a deep learning neural network to detect dangerous bacteria and harmful particles in water.(SDG 14)"
    elif x==7:
        return "AI can balance electricity supply and demand needs in real-time, optimize energy use and storage to reduce rates. Technology governance will be needed to democratize access, encourage innovation and ensure resilient electricity sources."
    elif x==8:
        return "It can increase the efficiency with which things are done and vastly improve the decision-making process by analysing large amounts of data. It can also spawn the creation of new products and services, markets and industries, thereby boosting consumer demand and generating new revenue streams."
    elif x==9:
        return "The demand for heavy data processing, like the large amounts of data generated by infrastructure projects, such as location-based services, requires advanced computing power and capabilities if it is to be processed effectively. AI can help achieve this by completing complex tasks in a fast and efficient manner."
    elif x==10:
        return "By incorporating AI into this process, we can remove that gender bias and undo that inequality, creating a company where candidates are truly hired based on merit over assumptions. In the government, there are many ways this technology could be implemented."
    elif x==11:
        return "Artificial intelligence (AI) has the potential to mitigate several issues facing cities, such as road safety, waste management, air pollution, and disaster risk reduction."
    elif x==12:
        return "AI is yielding optimal consumption and production levels with vertical green farms, eliminating waste and vastly improving yields and resource efficiency."
    elif x==13:
        return "AI applications could help design more energy-efficient buildings, improve power storage and optimise renewable energy deployment by feeding solar and wind power into the electricity grid as needed."
    elif x==14:
        return "Microscopic plankton species are key indicators for ocean pollution levels, since small changes in their health can point to much larger water quality issues and AI can measure it."
    elif x==15:
        return "AI has the potential to accelerate global efforts to protect the environment and conserve resources by detecting energy emission reductions, CO2 removal, helping develop greener transportation networks, monitoring deforestation, and predicting extreme weather conditions."
    elif x==16:
        return "With AI, the full amount of data across different institutions can be used to detect anomalies."
    else:
        return "AI technology solutions, machine learning (ML), big data, computer vision, and others, can help stakeholders get more concrete guidance on how to act towards achieving the SDGs. As one of the most emerging technologies, AI and ML will have a great impact on our future actions."


        
sg = ["No poverty","Zero hunger","Good wealth and well-being","Quality education","Gender equality","Clean water and sanitation",
      "Affordable and clean energy","Decent work and economic growth","Industry innovation and infrastructure",
      "Reduced inequalities","Sustainable cities and communities","Responsable comsumption and production",
      "Climate action","Life below water","Life on land","Peace, justice and strong institutions","Partnerships for the goals"]


sid = int(input("Enter a student ID number: "))
lim = sid + 17

print(f'ID: {sid}')
print("Choosing 2 different numbers", end = "")
time.sleep(1)
print('.', end = "")
time.sleep(1)
print('.', end = "")
time.sleep(1)
print('.')
time.sleep(1)

n1 = random.randint(sid,lim) - sid
print(f'Number {n1} - {sg[n1-1]}')
time.sleep(1.5)
print("How can AI contribute to this goal?")
time.sleep(2)
for letter in (defasolution(n1)):
    print(f'{letter}', end = "")
    time.sleep(0.025)

time.sleep(3)
n2 = random.randint(sid,lim) - sid
while(n2==n1):
    n2 = random.randint(sid,lim) - sid
print(f'\n\nNumber {n2} - {sg[n2-1]}')
time.sleep(1.5)
print("How can AI contribute to this goal?")
time.sleep(2)
for letter in (defasolution(n2)):
    print(f'{letter}', end = "")
    time.sleep(0.025)

time.sleep(2)
print("\n\nCode is finished byebye")
